### ISSUE TITLE
Check-ins (the feature, not the site) should have resizeable text entry fields

### ISSUE THREAD

**Issue by mitza-oci** [objectcomputing/check-ins#1565]
The form field that I'm typing in right now in github.com is resizable.  Please do the same on the .../checkins page.

**Comment by pieperm** [comment]
Check-Ins uses [react-quill](https://github.com/zenoamaro/react-quill) for its rich text fields. From the README:

> If you instantiate ReactQuill without children, it will create a `<div>` for you, to be used as the editing area for Quill. If you prefer, you can specify your own element for ReactQuill to use. Note that `<textarea>`s are not supported by Quill at this time.

I tinkered with the component to see if an MUI [`TextareaAutosize`](https://mui.com/base/react-textarea-autosize/) would work with it. As expected, it did not work, since `TextareaAutosize` uses `<textarea>`

**Comment by mkimberlin** [comment]
What about [TinyMCE](https://www.tiny.cloud/)? @zsbrown97 could you take a look and see if that will support our currently saved format? I can walk you through how to test that.

**Comment by mkimberlin** [comment]
This was added with the introduction of TinyMCE
