### ISSUE TITLE
Permissions not respected

### ISSUE THREAD

**Issue by mkimberlin** [objectcomputing/check-ins#2194]
**Describe the bug**
Something broke permissions. They aren't being respected when calls are made to the controllers.

**To Reproduce**
1. Remove any permission
2. Attempt to perform a related capability
3. Notice that it works regardless of the lack of permission

**Expected behavior**
I would expect unauthorized errors to be thrown

**Screenshots**
Case 1:
<img width="1510" alt="Screenshot 2024-04-16 at 12 08 06 PM" src="https://github.com/objectcomputing/check-ins/assets/100510/a5c40a7a-5902-40f7-b944-2ed896388426">

Case 2:
<img width="273" alt="Screenshot 2024-04-16 at 12 09 52 PM" src="https://github.com/objectcomputing/check-ins/assets/100510/6aef2705-5f56-48ae-af39-4398f0bcb393">
<img width="1558" alt="Screenshot 2024-04-16 at 12 09 39 PM" src="https://github.com/objectcomputing/check-ins/assets/100510/56454fba-9ea7-4788-80bd-7b3f65a0a089">

Case 3:
<img width="240" alt="Screenshot 2024-04-16 at 12 19 15 PM" src="https://github.com/objectcomputing/check-ins/assets/100510/74e99d2f-42ea-4d23-91e4-c4e2a5a4e217">
<img width="829" alt="Screenshot 2024-04-16 at 12 10 56 PM" src="https://github.com/objectcomputing/check-ins/assets/100510/41c6cfd0-af1f-4904-ab69-1614ed6e4f05">

**Additional context**
This is currently happening in the development environment

**Comment by ZacharyKlein** [comment]
The issue is that we are currently checking permissions (in `PermissionSecurityRule`) via the `permissions` claim on the user's JWT authentication. However, this claim is not updated when permissions are updated for a given role. Nor is there any way to update the token when permission/role assignments are changed (since this is a stateless auth flow). 

What's happening now is that the updated permissions _do_ take affect, after the user logs in again. So permissions _are_ respected, but any flow that keys off of the JWT (as the `PermissionSecurityRule` annotation does) is going to have to wait until the user's next login for that to take affect. 

I see two potential routes to improve this behavior:
1 - Programmatically force a re-login whenever a permission assignment changes for a role. 
2 - Update the flows that currently inspect the JWT for permissions, to instead use the user's role (like before), and then query the database for the current permission assignments for that role. 

I think #2 is the superior approach. It has a major downside in that it means we would be querying the database every time a secured route is accessed, however this could be minimized with smart caching of role/permission assignments, with explicit clearing of the cache whenever role/permission assignements are updated. I think if done correctly we can minimize the database interactions to basically once per role, until an update is made.
